version: '3.8'

services:
  influxdb:
    image: influxdb:1.8
    ports:
      - "8086:8086"
    environment:
      - INFLUXDB_DB=k6
    networks:
      - k6-network

  k6:
    image: grafana/k6:latest
    volumes:
      - ./scripts:/scripts
      - ./reports:/reports 
      - ./partial-results.json:/partial-results.json
    ports:
      - "5665:5665"
    depends_on:
      - influxdb
    environment:
      - K6_WEB_DASHBOARD=true
      # - K6_WEB_DASHBOARD_PORT=5665
      - K6_WEB_DASHBOARD_PERIOD=2s
      # - K6_WEB_DASHBOARD_OPEN=true
      - K6_WEB_DASHBOARD_EXPORT='report.html'
    command: run /scripts/scripttest-std-lib-go.js --out influxdb=http://influxdb:8086/k6
    networks:
      - test-network
      - payment-processor
      - k6-network

networks:
  k6-network:
    name: k6-network
    driver: bridge
  test-network:
    external: true
  payment-processor:
    external: true